# Generated by Django 5.2.13 on 2026-04-24 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('usage_limit', models.IntegerField(default=100)),
                ('uses_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cod_surcharge_percentage', models.DecimalField(decimal_places=2, default=2.0, help_text='Extra % added to COD orders (e.g. 2 = 2%)', max_digits=5)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('whatsapp_number', models.CharField(default='919709888456', help_text='Include country code, no + sign. e.g. 919709888456', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='UsageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Lucide icon name e.g. 'monitor', 'code', 'gamepad'", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sku', models.CharField(help_text='e.g. YC-LT-001', max_length=50, unique=True)),
                ('condition', models.CharField(choices=[('like_new', 'Like New'), ('excellent', 'Excellent'), ('good', 'Good'), ('value', 'Value')], default='excellent', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='MRP / original price for showing discount', max_digits=10, null=True)),
                ('processor', models.CharField(blank=True, max_length=255)),
                ('ram', models.CharField(blank=True, help_text='e.g. 8GB DDR4', max_length=50)),
                ('storage', models.CharField(blank=True, help_text='e.g. 256GB SSD', max_length=100)),
                ('display', models.CharField(blank=True, help_text='e.g. 14inch FHD', max_length=100)),
                ('graphics', models.CharField(blank=True, help_text='e.g. NVIDIA GTX 1650', max_length=100)),
                ('operating_system', models.CharField(blank=True, default='Windows 11 Pro', max_length=100)),
                ('battery', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('ports', models.CharField(blank=True, max_length=255)),
                ('wifi', models.CharField(blank=True, default='Wi-Fi 6', max_length=100)),
                ('bluetooth', models.CharField(blank=True, default='Bluetooth 5.0', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('highlights', models.TextField(blank=True, help_text='One highlight per line. e.g: Fast SSD\\nLong battery life')),
                ('refurbishment_summary', models.CharField(blank=True, default='40+ Quality Checks Passed', max_length=255)),
                ('refurbishment_points', models.TextField(blank=True, help_text='One point per line e.g: Battery Health: 92%\\nNo scratches')),
                ('warranty_summary', models.CharField(blank=True, default='6 Months Warranty', max_length=255)),
                ('warranty_details', models.TextField(blank=True, help_text='One detail per line e.g: Covers hardware defects\\n15-day return')),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_best_deal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
                ('usage_tags', models.ManyToManyField(blank=True, related_name='products', to='store.usagetag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('location', models.CharField(default='India', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(help_text='e.g. 8GB', max_length=50)),
                ('storage', models.CharField(help_text='e.g. 256GB SSD', max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price_override', models.DecimalField(decimal_places=2, default=0.0, help_text='Extra amount added to base price for this variant', max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'unique_together': {('product', 'ram', 'storage')},
            },
        ),
    ]
