# Generated by Django 5.2.13 on 2026-04-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.CharField(default='14 Days Return', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='service_centers',
            field=models.CharField(default='350+ Service Centers', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_period',
            field=models.CharField(default='1 Year Warranty', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cod_surcharge_percentage',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
    ]
