# Generated by Django 5.2.13 on 2026-04-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_return_policy_product_service_centers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='variant_info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
