# Generated by Django 5.2.13 on 2026-04-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_title', models.CharField(default='Our Vision', max_length=200)),
                ('vision_text', models.TextField(default="To make high-end computing accessible to everyone without sacrificing the planet's resources.")),
                ('mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('mission_text', models.TextField(default='Setting the gold standard in refurbishment through rigorous 50-step audits and industry-leading warranty support.')),
                ('about_image_1', models.ImageField(blank=True, null=True, upload_to='content/about/')),
                ('about_image_2', models.ImageField(blank=True, null=True, upload_to='content/about/')),
                ('heading', models.CharField(default='Crafting Excellence Since 2009', max_length=255)),
            ],
            options={
                'verbose_name': 'About Content',
                'verbose_name_plural': 'About Content',
            },
        ),
        migrations.CreateModel(
            name='BulkInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=100)),
                ('units_available', models.CharField(help_text='e.g. 500+ Units', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BulkOrderBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('truck', 'Truck / Delivery'), ('settings', 'Settings / Config'), ('shield', 'Shield / Security'), ('check', 'Check / Verified'), ('star', 'Star'), ('zap', 'Zap / Fast')], default='check', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BulkOrderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='content/bulk/')),
                ('hero_title', models.CharField(default='Equip Your Workspace.', max_length=255)),
                ('hero_title_highlight', models.CharField(default='Smartly.', max_length=100)),
                ('hero_subtitle', models.TextField(default="Transform your team's productivity with high-performance certified precision instruments. Access exclusive bulk discounts and dedicated enterprise support.")),
                ('section_heading', models.CharField(default='Scale Your Infrastructure Without Compromise.', max_length=255)),
                ('section_text', models.TextField(default='Our enterprise team is ready to build a custom quote that fits your budget and timeline. Expect a response within 2 working days.')),
                ('inventory_image', models.ImageField(blank=True, null=True, upload_to='content/bulk/')),
                ('inventory_heading', models.CharField(default='Ready for Deployment.', max_length=255)),
                ('inventory_text', models.TextField(default='We maintain ready stock of popular configurations to ensure your new hires start on day one without hardware delays.')),
            ],
            options={
                'verbose_name': 'Bulk Orders Page Content',
                'verbose_name_plural': 'Bulk Orders Page Content',
            },
        ),
        migrations.CreateModel(
            name='CompanyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='content/company/')),
                ('hero_title', models.CharField(default='Democratizing Technology Since 2009.', max_length=255)),
                ('hero_subtitle', models.CharField(blank=True, default='Yuva Computers', max_length=255)),
                ('story_heading', models.CharField(default='Our Journey Through Precision.', max_length=255)),
                ('story_text', models.TextField(default="We started with a simple belief: high-end technology shouldn't be a luxury. It should be a standard.")),
                ('vision_text', models.TextField(default='To eliminate digital obsolescence by creating a circular economy where technology is curated, not discarded.')),
                ('mission_text', models.TextField(default='Providing every professional with the tools they deserve through meticulous engineering and uncompromising quality standards.')),
                ('cta_heading', models.CharField(default='Experience it before you buy.', max_length=255)),
                ('cta_text', models.TextField(default='Visit our premium experience centers to test drive our curated selection of precision computing instruments.')),
            ],
            options={
                'verbose_name': 'Company Page Content',
                'verbose_name_plural': 'Company Page Content',
            },
        ),
        migrations.CreateModel(
            name='CompanyTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='content/hero/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RenameModel(
            old_name='HomeStat',
            new_name='SiteStat',
        ),
        migrations.DeleteModel(
            name='HomeAbout',
        ),
        migrations.DeleteModel(
            name='HomeHero',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
