# Generated by Django 5.2.13 on 2026-04-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_aboutcontent_bulkinventoryitem_bulkorderbenefit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkScalePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='e.g. Priority PAN-India Logistics', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Certified E-Recycler', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(help_text='e.g. Early Stage Growth', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. For Service', max_length=100)),
                ('number', models.CharField(help_text='e.g. +91 9347145456', max_length=30)),
                ('icon', models.CharField(choices=[('wrench', 'Wrench / Service'), ('shopping-cart', 'Cart / Sales'), ('message-square', 'Message / Complaints'), ('phone', 'Phone'), ('mail', 'Mail')], default='phone', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_heading', models.CharField(default="We're Here to Help.", max_length=255)),
                ('hero_subtext', models.TextField(default="Whether you're troubleshooting a workstation or planning a bulk deployment, our experts are ready.")),
                ('whatsapp_number', models.CharField(default='919709888456', max_length=20)),
                ('email_support', models.EmailField(default='info@yuvacomputers.in', max_length=254)),
                ('email_response_time', models.CharField(default='Response within 2 working days.', max_length=100)),
                ('grievance_officer_name', models.CharField(default='Rajender Kumar', max_length=100)),
                ('grievance_officer_email', models.EmailField(default='grievance@yuvacomputers.com', max_length=254)),
                ('branch_name', models.CharField(default='Dilshuknagar Main Branch', max_length=200)),
                ('branch_address', models.TextField(default='Metro Pillar No. 1519, Sai Towers, 204, 2nd Floor, above Tipsy Topsy Bakery, Dilsukhnagar, Hyderabad, TS 500060')),
                ('branch_hours', models.CharField(default='Daily: 10:00 AM - 08:30 PM', max_length=100)),
                ('branch_maps_url', models.URLField(default='https://maps.app.goo.gl/ChIJ3UKGZBCayzsRR8Nw_iIbU8g')),
                ('branch_maps_embed', models.TextField(blank=True, help_text='Full Google Maps embed src URL')),
            ],
            options={
                'verbose_name': 'Contact Page Content',
                'verbose_name_plural': 'Contact Page Content',
            },
        ),
        migrations.CreateModel(
            name='PartnerBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. DELL, HP, LENOVO', max_length=100)),
                ('color', models.CharField(blank=True, default='', help_text='Hex color e.g. #254fa0 (optional)', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Yuva Computers - Dilsukhnagar', max_length=200)),
                ('state', models.CharField(choices=[('Telangana', 'Telangana'), ('Andhra Pradesh', 'Andhra Pradesh')], default='Telangana', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('maps_url', models.URLField(blank=True, help_text='Google Maps URL')),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['state', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StoresPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_heading', models.CharField(default='Ready for Discovery? Explore Our Stores Today!', max_length=255)),
                ('page_subtext', models.TextField(default='Yuva Computers Physical Stores. Now proudly serving in 2 Major States.')),
                ('note_text', models.TextField(default="Please contact respective branches for the pricelist. To find our exact locations, search Google for 'Yuva Computers [Branch Area]' (e.g., 'Yuva Computers Warangal').")),
            ],
            options={
                'verbose_name': 'Stores Page Content',
                'verbose_name_plural': 'Stores Page Content',
            },
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='image_2_subtitle',
            field=models.CharField(default='We Made it Safe Work', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='image_2_title',
            field=models.CharField(default='Quality Control', max_length=100),
        ),
        migrations.AddField(
            model_name='companycontent',
            name='fueling_heading',
            field=models.CharField(default='Fueling the Future.', max_length=255),
        ),
        migrations.AddField(
            model_name='companycontent',
            name='fueling_subtext',
            field=models.CharField(default='Backed by leaders in sustainable tech and venture capital.', max_length=255),
        ),
        migrations.AddField(
            model_name='companycontent',
            name='integrity_heading',
            field=models.CharField(default='Integrity in Every Interaction.', max_length=255),
        ),
        migrations.AddField(
            model_name='companycontent',
            name='integrity_text',
            field=models.TextField(default='We partner with global leaders in electronics recycling and hardware certification.'),
        ),
        migrations.AddField(
            model_name='companycontent',
            name='partners_label',
            field=models.CharField(default='Our Partners', max_length=100),
        ),
        migrations.AlterField(
            model_name='bulkordercontent',
            name='hero_subtitle',
            field=models.TextField(default="Transform your team's productivity with certified refurbished devices."),
        ),
        migrations.AlterField(
            model_name='bulkordercontent',
            name='inventory_text',
            field=models.TextField(default='We maintain ready stock so your new hires start on day one.'),
        ),
        migrations.AlterField(
            model_name='bulkordercontent',
            name='section_text',
            field=models.TextField(default='Our enterprise team will build a custom quote within 2 working days.'),
        ),
    ]
