# Generated by Django 5.2.13 on 2026-04-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='exchange_coupon_code',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_defective',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='Ordered', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
