# Generated by Django 5.2.13 on 2026-04-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_accepted_return_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exchange_code_used',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='accepted_return_policy',
            field=models.BooleanField(default=True, help_text='Customer accepted 15-day exchange policy at checkout'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Refund Pending', 'Refund Pending')], default='Pending', max_length=20),
        ),
    ]
