# Generated by Django 5.2.13 on 2026-04-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_exchange_code_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='defect_video_url',
            field=models.URLField(blank=True, help_text='Link to video showing the defect (YouTube, Drive, etc.)', max_length=1000, null=True),
        ),
    ]
